# Generated by Django 4.1.7 on 2023-03-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Response123',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
                ('type_of', models.CharField(max_length=255)),
                ('languages', models.CharField(max_length=255)),
                ('month', models.CharField(max_length=25)),
                ('day', models.CharField(max_length=24)),
                ('time', models.CharField(max_length=25)),
                ('comment', models.CharField(max_length=1000)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
